apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.serviceName }}
    namespace: {{ .Values.namespace }}
spec:
    type: ClusterIP
    ports:
    - port: {{ .Values.port }}
      name: http
      targetPort: {{ .Values.port }}
    - port: 443
      name: https
      targetPort: 443
    selector:
      app: {{ .Values.serviceName}}
