import type { Metadata } from "next";
import AppMui from "@/mui/AppMui";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Educaverso",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({children}: Props) {
  return (
    <html lang="es">
      <body>
        <AppMui>
        {children}
        </AppMui>
      </body>
    </html>
  );
}
